// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvyg3JRmIEzYhTa5uBk9WpLVPtVUHzqdY',
    appId: '1:394594923252:web:329509a14f1763353364a1',
    messagingSenderId: '394594923252',
    projectId: 'tasky-61bb7',
    authDomain: 'tasky-61bb7.firebaseapp.com',
    storageBucket: 'tasky-61bb7.firebasestorage.app',
    measurementId: 'G-6M6DDVJFSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoW23kbvQxfOcJHYEPRlS7wRLYq7zeY2o',
    appId: '1:394594923252:android:b8f33ae0468e45c53364a1',
    messagingSenderId: '394594923252',
    projectId: 'tasky-61bb7',
    storageBucket: 'tasky-61bb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQXUJhT1IYHD4ezw-A-bVh5ra5k74qAg',
    appId: '1:394594923252:ios:1109d63d39b693ce3364a1',
    messagingSenderId: '394594923252',
    projectId: 'tasky-61bb7',
    storageBucket: 'tasky-61bb7.firebasestorage.app',
    iosBundleId: 'com.example.secondTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQXUJhT1IYHD4ezw-A-bVh5ra5k74qAg',
    appId: '1:394594923252:ios:1109d63d39b693ce3364a1',
    messagingSenderId: '394594923252',
    projectId: 'tasky-61bb7',
    storageBucket: 'tasky-61bb7.firebasestorage.app',
    iosBundleId: 'com.example.secondTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvyg3JRmIEzYhTa5uBk9WpLVPtVUHzqdY',
    appId: '1:394594923252:web:6e8176ece28fad8f3364a1',
    messagingSenderId: '394594923252',
    projectId: 'tasky-61bb7',
    authDomain: 'tasky-61bb7.firebaseapp.com',
    storageBucket: 'tasky-61bb7.firebasestorage.app',
    measurementId: 'G-EJLB99QQLP',
  );

}